// This file is auto-generated by @hey-api/openapi-ts

import type { Options as ClientOptions, TDataShape, Client } from './client';
import type { CheckDockerStatusData, CheckDockerStatusResponses, GetDockerOverviewData, GetDockerOverviewResponses, GetTopContainersData, GetTopContainersResponses, GetPerformanceWarningData, GetPerformanceWarningResponses, GetLatestLogData, GetLatestLogResponses, ListContainersData, ListContainersResponses, ListContainersErrors, GetContainerDetailsData, GetContainerDetailsResponses, GetContainerDetailsErrors, GetContainerLogsData, GetContainerLogsResponses, GetContainerLogsErrors, StartContainerData, StartContainerResponses, StartContainerErrors, StopContainerData, StopContainerResponses, StopContainerErrors, RestartContainerData, RestartContainerResponses, RestartContainerErrors, ListDockerImagesData, ListDockerImagesResponses, ListDockerVolumesData, ListDockerVolumesResponses, GetContainerVolumesData, GetContainerVolumesResponses, GetContainerVolumesErrors, GetDockerNetworksOverviewData, GetDockerNetworksOverviewResponses, GetDockerNetworkMapData, GetDockerNetworkMapResponses } from './types.gen';
import { client as _heyApiClient } from './client.gen';

export type Options<TData extends TDataShape = TDataShape, ThrowOnError extends boolean = boolean> = ClientOptions<TData, ThrowOnError> & {
    /**
     * You can provide a client instance returned by `createClient()` instead of
     * individual options. This might be also useful if you want to implement a
     * custom client.
     */
    client?: Client;
    /**
     * You can pass arbitrary values through the `meta` object. This can be
     * used to access values that aren't defined as part of the SDK function.
     */
    meta?: Record<string, unknown>;
};

/**
 * Check Docker Status
 */
export const checkDockerStatus = <ThrowOnError extends boolean = false>(options?: Options<CheckDockerStatusData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<CheckDockerStatusResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker-status',
        ...options
    });
};

/**
 * Get Docker Overview
 */
export const getDockerOverview = <ThrowOnError extends boolean = false>(options?: Options<GetDockerOverviewData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDockerOverviewResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/overview',
        ...options
    });
};

/**
 * Get Top Containers
 */
export const getTopContainers = <ThrowOnError extends boolean = false>(options?: Options<GetTopContainersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetTopContainersResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/top-containers',
        ...options
    });
};

/**
 * Get Performance Warning
 */
export const getPerformanceWarning = <ThrowOnError extends boolean = false>(options?: Options<GetPerformanceWarningData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetPerformanceWarningResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/performance-warning',
        ...options
    });
};

/**
 * Get Latest Log
 */
export const getLatestLog = <ThrowOnError extends boolean = false>(options?: Options<GetLatestLogData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetLatestLogResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/logs/latest',
        ...options
    });
};

/**
 * List Containers
 */
export const listContainers = <ThrowOnError extends boolean = false>(options?: Options<ListContainersData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListContainersResponses, ListContainersErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers',
        ...options
    });
};

/**
 * Get Container Details
 */
export const getContainerDetails = <ThrowOnError extends boolean = false>(options: Options<GetContainerDetailsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContainerDetailsResponses, GetContainerDetailsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}',
        ...options
    });
};

/**
 * Get Container Logs
 */
export const getContainerLogs = <ThrowOnError extends boolean = false>(options: Options<GetContainerLogsData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContainerLogsResponses, GetContainerLogsErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}/logs',
        ...options
    });
};

/**
 * Start Container
 */
export const startContainer = <ThrowOnError extends boolean = false>(options: Options<StartContainerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<StartContainerResponses, StartContainerErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}/start',
        ...options
    });
};

/**
 * Stop Container
 */
export const stopContainer = <ThrowOnError extends boolean = false>(options: Options<StopContainerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<StopContainerResponses, StopContainerErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}/stop',
        ...options
    });
};

/**
 * Restart Container
 */
export const restartContainer = <ThrowOnError extends boolean = false>(options: Options<RestartContainerData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).post<RestartContainerResponses, RestartContainerErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}/restart',
        ...options
    });
};

/**
 * List Docker Images
 */
export const listDockerImages = <ThrowOnError extends boolean = false>(options?: Options<ListDockerImagesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDockerImagesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/images',
        ...options
    });
};

/**
 * List Docker Volumes
 */
export const listDockerVolumes = <ThrowOnError extends boolean = false>(options?: Options<ListDockerVolumesData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<ListDockerVolumesResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/volumes',
        ...options
    });
};

/**
 * Get Container Volumes
 */
export const getContainerVolumes = <ThrowOnError extends boolean = false>(options: Options<GetContainerVolumesData, ThrowOnError>) => {
    return (options.client ?? _heyApiClient).get<GetContainerVolumesResponses, GetContainerVolumesErrors, ThrowOnError>({
        responseType: 'json',
        url: '/containers/{container_id}/volumes',
        ...options
    });
};

/**
 * Get Docker Networks Overview
 */
export const getDockerNetworksOverview = <ThrowOnError extends boolean = false>(options?: Options<GetDockerNetworksOverviewData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDockerNetworksOverviewResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/networks/overview',
        ...options
    });
};

/**
 * Get Docker Network Node Map
 */
export const getDockerNetworkMap = <ThrowOnError extends boolean = false>(options?: Options<GetDockerNetworkMapData, ThrowOnError>) => {
    return (options?.client ?? _heyApiClient).get<GetDockerNetworkMapResponses, unknown, ThrowOnError>({
        responseType: 'json',
        url: '/docker/networks/map',
        ...options
    });
};