// This file is auto-generated by @hey-api/openapi-ts

/**
 * AssignMultipleNetworksRequest
 */
export type AssignMultipleNetworksRequest = {
    /**
     * Network Names
     */
    network_names: Array<string>;
};

/**
 * AssignNetworkRequest
 */
export type AssignNetworkRequest = {
    /**
     * Network Name
     */
    network_name: string;
};

/**
 * AssignNetworkWithIPRequest
 */
export type AssignNetworkWithIpRequest = {
    /**
     * Network Name
     */
    network_name: string;
    /**
     * Ipv4 Address
     */
    ipv4_address?: string | null;
};

/**
 * AttachVolumeRequest
 */
export type AttachVolumeRequest = {
    /**
     * Volume Name
     */
    volume_name: string;
    /**
     * Mount Path
     */
    mount_path: string;
    /**
     * Read Only
     */
    read_only?: boolean;
};

/**
 * ContainerDetails
 */
export type ContainerDetails = {
    /**
     * Id
     * Short container ID
     */
    id: string;
    /**
     * Name
     * Container name
     */
    name: string;
    /**
     * Current container status
     */
    status: ContainerStatusEnum;
    /**
     * Image
     * List of container image tags
     */
    image: Array<string>;
    /**
     * Command
     * Startup command
     */
    command: string;
    /**
     * Created At
     * Timestamp of container creation (ISO 8601)
     */
    created_at: string;
    /**
     * Uptime Seconds
     * How long the container has been running (in seconds)
     */
    uptime_seconds?: number | null;
    /**
     * Ports
     * Published ports
     */
    ports?: Array<PortBinding>;
    /**
     * Error Count
     * Number of error events for the container
     */
    error_count?: number;
    /**
     * Latest Error Message
     * Most recent error message, if any
     */
    latest_error_message?: string | null;
    /**
     * Volumes
     */
    volumes: number;
    /**
     * Created
     * Raw container creation timestamp
     */
    created: string;
    /**
     * Platform
     * Platform or architecture (e.g. linux/amd64)
     */
    platform?: string | null;
    /**
     * Cpu Percent
     * Current CPU usage percentage
     */
    cpu_percent: number;
    /**
     * Memory Usage
     * Current memory usage in bytes
     */
    memory_usage: number;
    /**
     * Memory Limit
     * Memory limit in bytes
     */
    memory_limit: number;
    /**
     * Cpu Limit
     * CPU quota limit, if set (in cores)
     */
    cpu_limit?: number | null;
    /**
     * Mounts
     * List of mounted volumes/binds
     */
    mounts?: Array<MountInfo>;
    /**
     * Labels
     * User-defined metadata labels
     */
    labels?: {
        [key: string]: string;
    };
    /**
     * Env
     * List of environment variables
     */
    env?: Array<string>;
    /**
     * Restart Policy
     * Restart policy configuration
     */
    restart_policy?: {
        [key: string]: unknown;
    } | null;
    /**
     * Privileged
     * If the container is running in privileged mode
     */
    privileged?: boolean | null;
    /**
     * Log Path
     * Path to the container log file on the host
     */
    log_path?: string | null;
    /**
     * Entrypoint
     * Entrypoint for the container
     */
    entrypoint?: string | null;
    /**
     * Pid
     * Main process PID
     */
    pid?: number | null;
    /**
     * Exit Code
     * Exit code of the container if it has stopped
     */
    exit_code?: number | null;
    /**
     * State
     * Raw container state (e.g. running, exited)
     */
    state?: string | null;
    /**
     * Networks
     * All Docker networks connected to this container
     */
    networks?: Array<NetworkInfo>;
};

/**
 * ContainerLogsResponse
 */
export type ContainerLogsResponse = {
    /**
     * Logs
     */
    logs: Array<LogEntry>;
    /**
     * Next Since
     */
    next_since: number | null;
    /**
     * Count
     */
    count: number;
};

/**
 * ContainerNode
 */
export type ContainerNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Type
     */
    type: 'container';
    /**
     * Status
     */
    status: string;
    /**
     * Clusterid
     */
    clusterId: string | null;
};

/**
 * ContainerStats
 */
export type ContainerStats = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Cpu
     * CPU usage in percent
     */
    cpu: number;
    /**
     * Memory
     * Memory usage in percent
     */
    memory: number;
};

/**
 * ContainerStatusEnum
 */
export type ContainerStatusEnum = 'RUNNING' | 'STOPPED' | 'RESTARTED' | 'FAILED';

/**
 * ContainerSummary
 */
export type ContainerSummary = {
    /**
     * Id
     * Short container ID
     */
    id: string;
    /**
     * Name
     * Container name
     */
    name: string;
    /**
     * Current container status
     */
    status: ContainerStatusEnum;
    /**
     * Image
     * List of container image tags
     */
    image: Array<string>;
    /**
     * Command
     * Startup command
     */
    command: string;
    /**
     * Created At
     * Timestamp of container creation (ISO 8601)
     */
    created_at: string;
    /**
     * Uptime Seconds
     * How long the container has been running (in seconds)
     */
    uptime_seconds?: number | null;
    /**
     * Ports
     * Published ports
     */
    ports?: Array<PortBinding>;
    /**
     * Error Count
     * Number of error events for the container
     */
    error_count?: number;
    /**
     * Latest Error Message
     * Most recent error message, if any
     */
    latest_error_message?: string | null;
    /**
     * Volumes
     */
    volumes: number;
};

/**
 * CreateContainerRequest
 */
export type CreateContainerRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Image
     */
    image: string;
    /**
     * Command
     */
    command?: Array<string> | null;
    /**
     * Environment
     */
    environment?: {
        [key: string]: string;
    } | null;
    /**
     * Ports
     */
    ports?: {
        [key: string]: number;
    } | null;
    /**
     * Volume Mounts
     */
    volume_mounts?: Array<VolumeMount> | null;
    /**
     * Labels
     */
    labels?: {
        [key: string]: string;
    } | null;
    /**
     * Working Dir
     */
    working_dir?: string | null;
    /**
     * Entrypoint
     */
    entrypoint?: Array<string> | null;
    /**
     * User
     */
    user?: string | null;
    /**
     * Tty
     */
    tty?: boolean | null;
    /**
     * Detach
     */
    detach?: boolean;
    /**
     * Networks
     */
    networks?: Array<string> | null;
    restart_policy?: RestartPolicyModel | null;
    /**
     * Start After Create
     */
    start_after_create?: boolean | null;
    /**
     * Dry Run
     */
    dry_run?: boolean | null;
};

/**
 * CreateDockerNetworkRequest
 */
export type CreateDockerNetworkRequest = {
    /**
     * Name
     */
    name: string;
    /**
     * Driver
     */
    driver?: string;
    /**
     * Labels
     */
    labels?: {
        [key: string]: string;
    } | null;
    /**
     * Check Duplicate
     */
    check_duplicate?: boolean;
};

/**
 * CreateVolumeRequest
 */
export type CreateVolumeRequest = {
    /**
     * Name
     * The name of the Docker volume to create.
     */
    name: string;
    /**
     * Driver
     * The volume driver to use.
     */
    driver?: string | null;
    /**
     * Labels
     * Labels to apply to the volume.
     */
    labels?: {
        [key: string]: string;
    } | null;
    /**
     * Driver Opts
     * Driver-specific options.
     */
    driver_opts?: {
        [key: string]: string;
    } | null;
};

/**
 * CreatedVolumeResponse
 */
export type CreatedVolumeResponse = {
    /**
     * Name
     */
    name: string;
    /**
     * Driver
     */
    driver: string;
    /**
     * Mountpoint
     */
    mountpoint: string;
    /**
     * Created At
     */
    created_at?: string | null;
    /**
     * Labels
     */
    labels?: {
        [key: string]: string;
    } | null;
    /**
     * Options
     */
    options?: {
        [key: string]: string;
    } | null;
};

/**
 * DisconnectNetworkRequest
 */
export type DisconnectNetworkRequest = {
    /**
     * Network Name
     */
    network_name: string;
};

/**
 * DockerImageSummary
 */
export type DockerImageSummary = {
    /**
     * Id
     */
    id: string;
    /**
     * Tags
     */
    tags: Array<string>;
    /**
     * Size
     */
    size: number;
    /**
     * Created
     */
    created: string | null;
    /**
     * Architecture
     */
    architecture: string | null;
    /**
     * Os
     */
    os: string | null;
    /**
     * Containers
     * Containers using this image
     */
    containers?: Array<ImageContainerInfo>;
};

/**
 * DockerNetworkGraphResponse
 */
export type DockerNetworkGraphResponse = {
    /**
     * Nodes
     */
    nodes: Array<ContainerNode | NetworkNode>;
    /**
     * Links
     */
    links: Array<Link>;
};

/**
 * DockerNetworkOverview
 */
export type DockerNetworkOverview = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Driver
     */
    driver: string;
    /**
     * Scope
     */
    scope: string;
    /**
     * Containers Count
     */
    containers_count: number;
    /**
     * Running Containers Count
     */
    running_containers_count: number;
    /**
     * Labels
     */
    labels: {
        [key: string]: unknown;
    } | null;
    /**
     * Internal
     */
    internal: boolean;
    /**
     * Attachable
     */
    attachable: boolean;
    /**
     * Containers
     */
    containers: Array<NetworkContainerInfo>;
};

/**
 * DockerNetworkSelectItem
 */
export type DockerNetworkSelectItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    /**
     * Gateway
     */
    gateway?: string | null;
};

/**
 * DockerOverview
 */
export type DockerOverview = {
    /**
     * Version
     */
    version: string;
    /**
     * Total Containers
     */
    total_containers: number;
    /**
     * Running Containers
     */
    running_containers: number;
    /**
     * Failed Containers
     */
    failed_containers: number;
    /**
     * Images
     */
    images: number;
    /**
     * Volumes
     */
    volumes: number;
    /**
     * Logs Count
     */
    logs_count: number;
    /**
     * Is Swarm Active
     */
    is_swarm_active: boolean;
};

/**
 * DockerVolumeSummary
 */
export type DockerVolumeSummary = {
    /**
     * Name
     * Volume name (if named Docker volume)
     */
    name?: string | null;
    /**
     * Type
     * Type of mount: volume or bind
     */
    type: string;
    /**
     * Source
     * Host source path or volume name
     */
    source: string;
    /**
     * Destination
     * Mount point inside the container
     */
    destination: string;
    /**
     * Driver
     * Volume driver (Docker-managed only)
     */
    driver?: string | null;
    /**
     * Mountpoint
     * Where the volume is mounted on host
     */
    mountpoint?: string | null;
    /**
     * Created At
     * Creation timestamp (Docker volumes)
     */
    created_at?: string | null;
    /**
     * Size
     * Human-readable volume size (if available)
     */
    size?: string | null;
    /**
     * Labels
     * Metadata labels (Docker volumes)
     */
    labels?: {
        [key: string]: string;
    };
    /**
     * Containers
     * Containers using this volume
     */
    containers?: Array<VolumeContainerInfo>;
};

/**
 * GenericMessageResponse
 */
export type GenericMessageResponse = {
    /**
     * Success
     * Indicates if the operation was successful
     */
    success?: boolean | null;
    /**
     * Code
     * HTTP-like status code representing the outcome
     */
    code?: number | null;
    /**
     * Message
     * Human-readable message explaining the result
     */
    message?: string | null;
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * ImageContainerInfo
 */
export type ImageContainerInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    status: ContainerStatusEnum;
};

/**
 * Link
 */
export type Link = {
    /**
     * Source
     */
    source: string;
    /**
     * Target
     */
    target: string;
};

/**
 * LogEntry
 */
export type LogEntry = {
    /**
     * Timestamp
     */
    timestamp: string;
    /**
     * Message
     */
    message: string;
};

/**
 * LogInfo
 */
export type LogInfo = {
    /**
     * Count
     * Total number of log entries
     */
    count: number;
    /**
     * Latest
     * Most recent log message
     */
    latest: string;
};

/**
 * MountInfo
 */
export type MountInfo = {
    /**
     * Source
     * Host path or volume name
     */
    source?: string | null;
    /**
     * Destination
     * Mount point inside the container
     */
    destination: string;
    /**
     * Mode
     * Read/write mode (e.g. 'rw')
     */
    mode?: string | null;
    /**
     * Type
     * Mount type (e.g. 'bind', 'volume')
     */
    type?: string | null;
};

/**
 * NetworkContainerInfo
 */
export type NetworkContainerInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string | null;
    /**
     * Status
     */
    status: string | null;
    /**
     * Ipv4 Address
     */
    ipv4_address: string | null;
};

/**
 * NetworkInfo
 */
export type NetworkInfo = {
    /**
     * Name
     */
    name: string;
    /**
     * Id
     */
    id: string;
    /**
     * Ip Address
     */
    ip_address?: string | null;
    /**
     * Driver
     */
    driver?: string | null;
    /**
     * Gateway
     */
    gateway?: string | null;
    /**
     * Subnet
     */
    subnet?: string | null;
    /**
     * Internal
     */
    internal?: boolean | null;
    /**
     * Attachable
     */
    attachable?: boolean | null;
};

/**
 * NetworkNode
 */
export type NetworkNode = {
    /**
     * Id
     */
    id: string;
    /**
     * Label
     */
    label: string;
    /**
     * Type
     */
    type: 'network';
};

/**
 * PerformanceWarning
 */
export type PerformanceWarning = {
    /**
     * Message
     */
    message: string;
};

/**
 * PortBinding
 */
export type PortBinding = {
    /**
     * Container Port
     * Port exposed in container (e.g. '80/tcp')
     */
    container_port: string;
    /**
     * Host Ip
     * Host IP (if published)
     */
    host_ip?: string | null;
    /**
     * Host Port
     * Published host port (if any)
     */
    host_port?: string | null;
};

/**
 * PullImageRequest
 */
export type PullImageRequest = {
    /**
     * Repository
     */
    repository: string;
    /**
     * Tag
     */
    tag?: string;
};

/**
 * RestartPolicyModel
 */
export type RestartPolicyModel = {
    /**
     * Name
     */
    name: 'no' | 'always' | 'unless-stopped' | 'on-failure';
    /**
     * Maximum Retry Count
     */
    maximum_retry_count?: number | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

/**
 * VolumeContainerInfo
 */
export type VolumeContainerInfo = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
    status: ContainerStatusEnum;
    /**
     * Mountpoint
     */
    mountpoint?: string | null;
};

/**
 * VolumeMount
 */
export type VolumeMount = {
    /**
     * Volume Name
     */
    volume_name: string;
    /**
     * Mount Path
     */
    mount_path: string;
    /**
     * Read Only
     */
    read_only?: boolean | null;
};

/**
 * VolumeSelectList
 */
export type VolumeSelectList = {
    /**
     * Volumes
     */
    volumes: Array<VolumeSelectListItem>;
};

/**
 * VolumeSelectListItem
 */
export type VolumeSelectListItem = {
    /**
     * Id
     */
    id: string;
    /**
     * Name
     */
    name: string;
};

export type CheckDockerStatusData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker-status';
};

export type CheckDockerStatusResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type CheckDockerStatusResponse = CheckDockerStatusResponses[keyof CheckDockerStatusResponses];

export type GetDockerOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/overview';
};

export type GetDockerOverviewResponses = {
    /**
     * Successful Response
     */
    200: DockerOverview;
};

export type GetDockerOverviewResponse = GetDockerOverviewResponses[keyof GetDockerOverviewResponses];

export type GetTopContainersData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/top-containers';
};

export type GetTopContainersResponses = {
    /**
     * Response Gettopcontainers
     * Successful Response
     */
    200: Array<ContainerStats>;
};

export type GetTopContainersResponse = GetTopContainersResponses[keyof GetTopContainersResponses];

export type GetPerformanceWarningData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/performance-warning';
};

export type GetPerformanceWarningResponses = {
    /**
     * Successful Response
     */
    200: PerformanceWarning;
};

export type GetPerformanceWarningResponse = GetPerformanceWarningResponses[keyof GetPerformanceWarningResponses];

export type GetLatestLogData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/logs/latest';
};

export type GetLatestLogResponses = {
    /**
     * Successful Response
     */
    200: LogInfo;
};

export type GetLatestLogResponse = GetLatestLogResponses[keyof GetLatestLogResponses];

export type ListContainersData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * All
         * Show all containers, including stopped
         */
        all?: boolean;
    };
    url: '/containers';
};

export type ListContainersErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ListContainersError = ListContainersErrors[keyof ListContainersErrors];

export type ListContainersResponses = {
    /**
     * Response Listcontainers
     * Successful Response
     */
    200: Array<ContainerSummary>;
};

export type ListContainersResponse = ListContainersResponses[keyof ListContainersResponses];

export type DeleteContainerData = {
    body?: never;
    path: {
        /**
         * Container Id
         * Container ID or name
         */
        container_id: string;
    };
    query?: {
        /**
         * Force
         * Force remove running container
         */
        force?: boolean;
    };
    url: '/containers/{container_id}';
};

export type DeleteContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteContainerError = DeleteContainerErrors[keyof DeleteContainerErrors];

export type DeleteContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type DeleteContainerResponse = DeleteContainerResponses[keyof DeleteContainerResponses];

export type GetContainerDetailsData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}';
};

export type GetContainerDetailsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerDetailsError = GetContainerDetailsErrors[keyof GetContainerDetailsErrors];

export type GetContainerDetailsResponses = {
    /**
     * Successful Response
     */
    200: ContainerDetails;
};

export type GetContainerDetailsResponse = GetContainerDetailsResponses[keyof GetContainerDetailsResponses];

export type GetContainerLogsData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: {
        /**
         * Tail
         */
        tail?: number;
        /**
         * Since
         * Unix timestamp to start from
         */
        since?: number | null;
        /**
         * Until
         * Unix timestamp to end at
         */
        until?: number | null;
    };
    url: '/containers/{container_id}/logs';
};

export type GetContainerLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerLogsError = GetContainerLogsErrors[keyof GetContainerLogsErrors];

export type GetContainerLogsResponses = {
    /**
     * Successful Response
     */
    200: ContainerLogsResponse;
};

export type GetContainerLogsResponse = GetContainerLogsResponses[keyof GetContainerLogsResponses];

export type StartContainerData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/start';
};

export type StartContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StartContainerError = StartContainerErrors[keyof StartContainerErrors];

export type StartContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type StartContainerResponse = StartContainerResponses[keyof StartContainerResponses];

export type StopContainerData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/stop';
};

export type StopContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StopContainerError = StopContainerErrors[keyof StopContainerErrors];

export type StopContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type StopContainerResponse = StopContainerResponses[keyof StopContainerResponses];

export type RestartContainerData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/restart';
};

export type RestartContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RestartContainerError = RestartContainerErrors[keyof RestartContainerErrors];

export type RestartContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type RestartContainerResponse = RestartContainerResponses[keyof RestartContainerResponses];

export type ListDockerImagesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/images';
};

export type ListDockerImagesResponses = {
    /**
     * Response Listdockerimages
     * Successful Response
     */
    200: Array<DockerImageSummary>;
};

export type ListDockerImagesResponse = ListDockerImagesResponses[keyof ListDockerImagesResponses];

export type ListDockerVolumesData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/volumes';
};

export type ListDockerVolumesResponses = {
    /**
     * Response Listdockervolumes
     * Successful Response
     */
    200: Array<DockerVolumeSummary>;
};

export type ListDockerVolumesResponse = ListDockerVolumesResponses[keyof ListDockerVolumesResponses];

export type CreateDockerVolumeData = {
    body: CreateVolumeRequest;
    path?: never;
    query?: never;
    url: '/volumes';
};

export type CreateDockerVolumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDockerVolumeError = CreateDockerVolumeErrors[keyof CreateDockerVolumeErrors];

export type CreateDockerVolumeResponses = {
    /**
     * Successful Response
     */
    200: CreatedVolumeResponse;
};

export type CreateDockerVolumeResponse = CreateDockerVolumeResponses[keyof CreateDockerVolumeResponses];

export type DeleteDockerVolumeData = {
    body?: never;
    path: {
        /**
         * Volume Name
         */
        volume_name: string;
    };
    query?: never;
    url: '/volumes/{volume_name}';
};

export type DeleteDockerVolumeErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDockerVolumeError = DeleteDockerVolumeErrors[keyof DeleteDockerVolumeErrors];

export type DeleteDockerVolumeResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type DeleteDockerVolumeResponse = DeleteDockerVolumeResponses[keyof DeleteDockerVolumeResponses];

export type GetContainerVolumesData = {
    body?: never;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/volumes';
};

export type GetContainerVolumesErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type GetContainerVolumesError = GetContainerVolumesErrors[keyof GetContainerVolumesErrors];

export type GetContainerVolumesResponses = {
    /**
     * Response Getcontainervolumes
     * Successful Response
     */
    200: Array<DockerVolumeSummary>;
};

export type GetContainerVolumesResponse = GetContainerVolumesResponses[keyof GetContainerVolumesResponses];

export type GetDockerNetworksOverviewData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/networks/overview';
};

export type GetDockerNetworksOverviewResponses = {
    /**
     * Response Getdockernetworksoverview
     * Successful Response
     */
    200: Array<DockerNetworkOverview>;
};

export type GetDockerNetworksOverviewResponse = GetDockerNetworksOverviewResponses[keyof GetDockerNetworksOverviewResponses];

export type GetDockerNetworkMapData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/networks/map';
};

export type GetDockerNetworkMapResponses = {
    /**
     * Successful Response
     */
    200: DockerNetworkGraphResponse;
};

export type GetDockerNetworkMapResponse = GetDockerNetworkMapResponses[keyof GetDockerNetworkMapResponses];

export type StreamPullWithSummaryData = {
    body: PullImageRequest;
    path?: never;
    query?: never;
    url: '/images/pull/full';
};

export type StreamPullWithSummaryErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type StreamPullWithSummaryError = StreamPullWithSummaryErrors[keyof StreamPullWithSummaryErrors];

export type StreamPullWithSummaryResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ListDockerVolumesLiteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/volumes/list';
};

export type ListDockerVolumesLiteResponses = {
    /**
     * Successful Response
     */
    200: VolumeSelectList;
};

export type ListDockerVolumesLiteResponse = ListDockerVolumesLiteResponses[keyof ListDockerVolumesLiteResponses];

export type AttachVolumeToContainerData = {
    body: AttachVolumeRequest;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/attach-volume';
};

export type AttachVolumeToContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AttachVolumeToContainerError = AttachVolumeToContainerErrors[keyof AttachVolumeToContainerErrors];

export type AttachVolumeToContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type AttachVolumeToContainerResponse = AttachVolumeToContainerResponses[keyof AttachVolumeToContainerResponses];

export type CreateContainerWithLogsData = {
    body: CreateContainerRequest;
    path?: never;
    query?: never;
    url: '/containers/create';
};

export type CreateContainerWithLogsErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateContainerWithLogsError = CreateContainerWithLogsErrors[keyof CreateContainerWithLogsErrors];

export type CreateContainerWithLogsResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type DeleteDockerImageData = {
    body?: never;
    path: {
        /**
         * Image Id
         */
        image_id: string;
    };
    query?: never;
    url: '/images/{image_id}';
};

export type DeleteDockerImageErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDockerImageError = DeleteDockerImageErrors[keyof DeleteDockerImageErrors];

export type DeleteDockerImageResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type DeleteDockerImageResponse = DeleteDockerImageResponses[keyof DeleteDockerImageResponses];

export type DeleteDockerNetworkData = {
    body?: never;
    path: {
        /**
         * Network Id
         */
        network_id: string;
    };
    query?: {
        /**
         * Dry Run
         * If true, only preview whether the network can be deleted
         */
        dry_run?: boolean;
    };
    url: '/docker/networks/{network_id}';
};

export type DeleteDockerNetworkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DeleteDockerNetworkError = DeleteDockerNetworkErrors[keyof DeleteDockerNetworkErrors];

export type DeleteDockerNetworkResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type DeleteDockerNetworkResponse = DeleteDockerNetworkResponses[keyof DeleteDockerNetworkResponses];

export type CreateDockerNetworkData = {
    body: CreateDockerNetworkRequest;
    path?: never;
    query?: never;
    url: '/docker/networks';
};

export type CreateDockerNetworkErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type CreateDockerNetworkError = CreateDockerNetworkErrors[keyof CreateDockerNetworkErrors];

export type CreateDockerNetworkResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type CreateDockerNetworkResponse = CreateDockerNetworkResponses[keyof CreateDockerNetworkResponses];

export type AssignNetworkToContainerData = {
    body: AssignNetworkRequest;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/assign-network';
};

export type AssignNetworkToContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignNetworkToContainerError = AssignNetworkToContainerErrors[keyof AssignNetworkToContainerErrors];

export type AssignNetworkToContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type AssignNetworkToContainerResponse = AssignNetworkToContainerResponses[keyof AssignNetworkToContainerResponses];

export type DisconnectNetworkFromContainerData = {
    body: DisconnectNetworkRequest;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/disconnect-network';
};

export type DisconnectNetworkFromContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type DisconnectNetworkFromContainerError = DisconnectNetworkFromContainerErrors[keyof DisconnectNetworkFromContainerErrors];

export type DisconnectNetworkFromContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type DisconnectNetworkFromContainerResponse = DisconnectNetworkFromContainerResponses[keyof DisconnectNetworkFromContainerResponses];

export type AssignMultipleNetworksToContainerData = {
    body: AssignMultipleNetworksRequest;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/assign-networks';
};

export type AssignMultipleNetworksToContainerErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignMultipleNetworksToContainerError = AssignMultipleNetworksToContainerErrors[keyof AssignMultipleNetworksToContainerErrors];

export type AssignMultipleNetworksToContainerResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type AssignMultipleNetworksToContainerResponse = AssignMultipleNetworksToContainerResponses[keyof AssignMultipleNetworksToContainerResponses];

export type AssignNetworkWithStaticIpData = {
    body: AssignNetworkWithIpRequest;
    path: {
        /**
         * Container Id
         */
        container_id: string;
    };
    query?: never;
    url: '/containers/{container_id}/assign-network-ip';
};

export type AssignNetworkWithStaticIpErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AssignNetworkWithStaticIpError = AssignNetworkWithStaticIpErrors[keyof AssignNetworkWithStaticIpErrors];

export type AssignNetworkWithStaticIpResponses = {
    /**
     * Successful Response
     */
    200: GenericMessageResponse;
};

export type AssignNetworkWithStaticIpResponse = AssignNetworkWithStaticIpResponses[keyof AssignNetworkWithStaticIpResponses];

export type ListDockerNetworksLiteData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/docker/networks/list';
};

export type ListDockerNetworksLiteResponses = {
    /**
     * Response Listdockernetworkslite
     * Successful Response
     */
    200: Array<DockerNetworkSelectItem>;
};

export type ListDockerNetworksLiteResponse = ListDockerNetworksLiteResponses[keyof ListDockerNetworksLiteResponses];

export type ClientOptions = {
    baseURL: 'http://localhost:8000' | (string & {});
};