version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: web
    networks:
      - frontend
    ports:
      - "8080:80"

  app:
    image: node:18-alpine
    container_name: app
    command: sh -c "while true; do echo Hello from App; sleep 5; done"
    networks:
      - frontend
      - backend

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
