version: "3.8"

services:
  web:
    image: nginx:latest
    container_name: web
    networks:
      - frontend
    ports:
      - "8080:80"

  app:
    image: node:18-alpine
    container_name: app
    command: sh -c "while true; do echo Hello from App; sleep 5; done"
    networks:
      - frontend
      - backend

  db:
    image: postgres:16-alpine
    container_name: db
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: appdb
    networks:
      - backend

  cache:
    image: redis:7-alpine
    container_name: cache
    networks:
      - cache_net

  worker:
    image: python:3.12-alpine
    container_name: worker
    command: sh -c "while true; do echo Worker running...; sleep 10; done"
    networks:
      - backend
      - worker_net

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge
  cache_net:
    driver: bridge
  worker_net:
    driver: bridge
